# Generated by Django 3.2.20 on 2023-09-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='post',
        ),
    ]
