# Generated by Django 3.2.20 on 2023-09-03 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votes', '0002_alter_vote_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
